language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - ruby-head
  - jruby-19mode
  - rbx

jdk:
  - oraclejdk8

env: 
  - JARS_VERBOSE=true
  - cool.io.debug=true

matrix:
  allow_failures:
    - rvm: rbx
